dist: trusty
sudo: false

branches:
  except:
    - gh-pages

language: node_js
node_js:
  - "8.9.4"

before_script:
  - npm install -g @angular/cli@7.3.9

script: 
  - npm run build-prod

deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist/web-cross/
  on:
    branch: master
